---
title: "Conclusion and further readings"
bibliography: references.bib
---

This project investigates the relationships between public health and population dynamics using World Bank data to reveal patterns across regions and income levels. Focusing on three indicator pairs, we analyze how demographic and health factors interact, including adolescent fertility rate and population growth, age dependency ratio and life expectancy at birth, and births attended by skilled health staff and infant mortality rates.

Both pairs 1 and 2 supported trends across countries of different income groups, attributed to phenomena associated with demographic transition. Low income countries have experienced the greatest decreases in adolescent fertility rates but also the largest increase in population growth rates. This highlights the fact that fertility rates in not adolescents, but older population as well as a country's overall improvements in areas such as access to food, healthcare, sanitation, and economic development. Likewise, the more pronounced decreases in dependency ratios lower-middle and upper-middle income countries as they transition to highly developed economies reflect a shift in the demographics working class to older groups, as well as also having a more pronounced increase in life expectancy as opposed to highly developed countries, where life expectancy is already approaching its human limits. These indicators and their trajectories aren't necessarily the sole cause of one another, but are intertwined with and influence one another and change accordingly with a country's point along demographic transition into highly developed economies.

For pair 3, the analysis shows that increased skilled birth attendance is strongly associated with declines in infant mortality globally, with significant progress in regions like Sub-Saharan Africa and South Asia despite ongoing disparities. A systematic review of 41 African countries demonstrated that a 10% increase in skilled birth attendance corresponded with a 6% reduction in neonatal mortality, highlighting the critical impact of skilled healthcare during childbirth on infant survival [@berhan2014skilled]. Similarly, a national survey in Lesotho found that births not attended by skilled health personnel had twice the risk of neonatal death compared to those with skilled attendants, directly supporting the finding that increased skilled birth attendance is linked to lower infant mortality rates [@baruwa2021association].
