---
title: "Age dependency vs. Life expectancy"
bibliography: references.bib
---

```{python}
#| echo: false
from IPython.display import Image
Image("../figures/2scatter.png")
```

The countries belonging the regions of Sub-Saharan Africa and Europe & Central Asia share the most similarities with other countries within their own regions. Both these regions have experienced a relatively small change in age dependency, while most other regions seem to have undergone a more significant decrease in age dependency. Globally, all countries experienced an increase in life expectancy, with Europe & Central Asia in particular having experienced the smallest change.

```{python}
#| echo: false
from IPython.display import Image
Image("../figures/2expectancy_across_income.png")
```

High income countries experienced relatively small increase in life expectancy on average while lower-middle income countries experienced the most significant increase in life expectancy. Low income countries experienced an increase just slightly shy of that of lower-middle income countries and ahve the narrowest distribution of change. However, high income and upper-middle income countries had the widest range in life expectancy changes—they include countries that experienced the greatest increases of 40 years, and some as low as under 5 years.

```{python}
#| echo: false
from IPython.display import Image
Image("../figures/2faceted.png")
```

High income countries of Europe & Central Asia are clustered near one another in both age dependency and life expectancy change, and upper-middle income countries of the same region also have similar change in age dependency. Countries in the Latin America & Caribbean region also have a relatively substantial decrease in age dependency, most prominent in the region's upper middle income countries. Low income countries, however, seem to have experienced the smallest decrease in age dependency.

In the future, increases in age dependency ratios are predicted to occur in regions with generally increasing populations such as the regions of Sub-Saharan Africa, Middle East, Asia, and Latin America, while established market economies such as those in Europe and Japan will experience increasing age dependency ratios [@harwood2004current]. These trends of age dependency are not necessarily reflected in our data, as countries in the Middle East, Latin America, and Asia are shown to have experienced decreasing age dependency ratios while Sub-Saharan African countries have less of a pronounced change in age dependency ratios. Additionally, within the early stages of demographic transition, life expectancies tend to increase and begin to stagnate in later stages, which is reflected by high income countries having relatively small increases in life expectancy. As part of demographic transition, age of entry into the workforce is also pushed back, while elderly populations can still remain active within the workforce with higher ages of retirement [@pablos2015demographic]. Paired with this fact, countries that are in the intermediate stages of demographic transition are likely to experience decreasing age dependency ratios as the population pyramid narrows and the proportion of the youth population decreases, drastically decreasing the amount of youth dependents while at the same time, elderly populations are also more likely to work and contribute to the workforce. This trend is also reflected in our data, where upper-middle and lower-middle income countries have experienced more significant decreases on average as they have undergone further transition into more developed economies.

